GET http://localhost:8000/secTask/5f5b174b4b24f337b04ff0bd HTTP/1.1
# content-type: application/json

# {
#     "secTask": {
#         "name" : "Develop Backend",
#         "section" : "UpComing"
#     },
    # "projId": "5f5b174b4b24f337b04ff0bd"
# }